HOST: http://localhost/

--- Ročníkový Projekt API ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Ucitele Resources
The following is a section of resources related to Ucitele
--


Seznam ucitelu
GET /ucitele
< 200
< Content-Type: application/json
{ "ucitele": [
    { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
    { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"},
    { "id": 3, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"},
    { "id": 4, "jmeno": "Jacob4", "prijmeni": "Slezstromu4", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
] }


Detail ucitele
GET /ucitele/{id}
< 200
< Content-Type: application/json
{ "id": 2, "jmeno": "Jon", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}


Vytvoreni noveho ucitele
POST /ucitele
> Content-Type: application/json
{ "jmeno": "Jan", "prijmeni": "Řendiblech", "autoskola-id": 1, "opravneni": ["A", "C"], "pocet-deti" : 0, "datum-prohlidky": "2013-01-01" }
< 201
< Content-Type: application/json
{ "id": 3 }


--
Autoskoly Resources
The following is a section of resources related to Autoskoly
--

Seznam autoskol
GET /autoskoly
< 200
< Content-Type: application/json
{ "autoskoly": [
    { "id": 1, "nazev": "Aotoskola1", "ucitele" : [
        { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
        { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
    ], "vozidla": [
        { "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1}
    ]}, { "id": 2, "nazev": "Autoskola2", "ucitele" : [
        { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
        { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
    ], "vozidla": [
        { "id": 1, "znacka": "Skoda", "model": "Octavia", "vin": "LJP05GFD5548913", "autoskola-id": 2 }
    ]}
] }

Detail autoskoly
GET /autoskoly/{id}
< 200
< Content-Type: application/json
{ "id": 1, "nazev": "Aotoskola1", "ucitele" : [
        { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
        { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
    ], "vozidla": [
        { "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1}
    ]
}


--
Vozidla Resources
The following is a section of resources related to Vozidla
--

Seznam vozidel
GET /vozidla
< 200
< Content-Type: application/json
{ "vozidla": [
    { "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1},
    { "id": 2, "znacka": "Skoda", "model": "Octavia", "vin": "LJP05GFD5541111", "autoskola-id": 2 }
] }


Detail vozidla
GET /vozidla/{id}
< 200
< Content-Type: application/json
{ "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1, "pocet-km" : 155555, "datum-stk": "2014-05-01", "pocatecni-stav-km": 30000,
  "jizdy" : [
    { "id": 1, "datum": "2013-01-01", "ucitel": 2, "vozidlo": 1, "zak": 1, "doba-jizdy": "02:00", "pocet-ujetych-km" : 15, "spotreba" : 6.7 },
    { "id": 2, "datum": "2013-01-01", "ucitel": 1, "vozidlo": 1, "zak": 5, "doba-jizdy": "01:50", "pocet-ujetych-km" : 16, "spotreba" : 7.1 }
] }

Vytvoreni noveho vozidla
POST /vozidla
> Content-Type: application/json
{ "id": 3, "znacka": "Ford", "model": "Mondeo", "vin": "LJP05GFD5542222", "autoskola-id": 1 }
< 201
< Content-Type: application/json
{ "id": 3 }

Odstraneni vozidla
DELETE /vozidla/{id}
> Content-Type: application/json
{ "id": 3, "znacka": "Ford", "model": "Mondeo", "vin": "LJP05GFD5542222", "autoskola-id": 1, "pocatecni-stav-km": 30000 }
< 200
< Content-Type: application/json
{ "id": 3 }

Kniha jizdy
GET /jizdy
< 200
< Content-Type: application/json
{ "ucitele": [
    { "id": 1, "datum": "2013-01-01", "ucitel": 2, "vozidlo": 1, "zak": 1, "doba-jizdy": "02:00", "pocet-ujetych-km" : 15, "spotreba" : 6.7 },
    { "id": 2, "datum": "2013-01-01", "ucitel": 1, "vozidlo": 1, "zak": 5, "doba-jizdy": "01:50", "pocet-ujetych-km" : 16, "spotreba" : 7.1 }
] }