HOST: http://localhost/

--- Ročníkový Projekt API ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Ucitele Resources 
The following is a section of resources related to Ucitele
--


Seznam ucitelu
GET /ucitele
< 200
< Content-Type: application/json
{ "ucitele": [
    { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
    { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"},
    { "id": 3, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"},
    { "id": 4, "jmeno": "Jacob4", "prijmeni": "Slezstromu4", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
] }


Detail ucitele
GET /ucitele/{id}
< 200
< Content-Type: application/json
{ "id": 2, "jmeno": "Jon", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}


Vytvoreni noveho ucitele
POST /ucitele
> Content-Type: application/json
{ "jmeno": "Jan", "prijmeni": "Řendiblech", "autoskola-id": 1, "opravneni": ["A", "C"], "pocet-deti" : 0, "datum-prohlidky": "2013-01-01" }
< 201
< Content-Type: application/json
{ "id": 3 }


--
Studenti Resources
The following is a section of resources related to Studenti
--


Seznam studentu
GET /studenti
< 200
< Content-Type: application/json
{ "studenti": [
    { "id": 1, "jmeno": "Martin", "prijmeni": "ZborilGaraz", "autoskola-id": 1, "matricni-cislo": 26549562 },
    { "id": 2, "jmeno": "Jacob", "prijmeni": "VjelDoPole", "autoskola-id": 1, "matricni-cislo": 26549562 },
    { "id": 3, "jmeno": "Lukas", "prijmeni": "SrazilChodce", "autoskola-id": 1, "matricni-cislo": 26549562 },
    { "id": 4, "jmeno": "Lukas", "prijmeni": "SrazilChodce", "autoskola-id": 2, "matricni-cislo": 26549562 }
] }


Detail studenta
GET /studenti/{id}
< 200
< Content-Type: application/json
{ "id": 1, "jmeno": "Martin", "prijmeni": "ZborilGaraz", "autoskola-id": 1, "matricni-cislo": 26549562 }


Vytvoreni noveho studenta
POST /studenti
> Content-Type: application/json
{ "jmeno": "Martin", "prijmeni": "ZborilGaraz", "autoskola-id": 1, "matricni-cislo": 26549562 }
< 201
< Content-Type: application/json
{ "id": 3 }


--
Autoskoly Resources
The following is a section of resources related to Autoskoly
--

Seznam autoskol
GET /autoskoly
< 200
< Content-Type: application/json
{ "autoskoly": [
    { "id": 1, "nazev": "Aotoskola1", "ucitele" : [
        { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
        { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
    ], "vozidla": [
        { "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1}
    ]}, { "id": 2, "nazev": "Autoskola2", "ucitele" : [
        { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
        { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
    ], "vozidla": [
        { "id": 1, "znacka": "Skoda", "model": "Octavia", "vin": "LJP05GFD5548913", "autoskola-id": 2 }
    ]}
] }

Detail autoskoly
GET /autoskoly/{id}
< 200
< Content-Type: application/json
{ "id": 1, "nazev": "Aotoskola1", "pocet-ucitelu": 3, "pocet-vozidel": 5, "pocet-aktivnich-kurzu": 4, "ucitele": [
        { "id": 1, "jmeno": "Martin", "prijmeni": "Skočdopole", "autoskola-id": 1, "opravneni": ["A", "B"], "pocet-deti" : 2, "datum-prohlidky": "2013-01-01", "url-dokumentu": "/prohlidky/asdasdasdad.pdf"},
        { "id": 2, "jmeno": "Jacob", "prijmeni": "Slezstromu", "autoskola-id": 2, "opravneni": ["T"], "pocet-deti" : 0, "datum-prohlidky": "2013-05-01", "url-dokumentu": "/prohlidky/dddddfd.jpg"}
    ], "vozidla": [
        { "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1}
    ], "aktualni-studenti" : [
        { "id": 1, "jmeno": "Martin", "prijmeni": "ZborilGaraz", "autoskola-id": 1, "matricni-cislo": 26549562},
        { "id": 2, "jmeno": "Jacob", "prijmeni": "VjelDoPole", "autoskola-id": 1, "matricni-cislo": 26549562},
        { "id": 3, "jmeno": "Lukas", "prijmeni": "SrazilChodce", "autoskola-id": 1, "matricni-cislo": 26549562}
    ]
}


--
Kurzy Resources
The following is a section of resources related to Vozidla
--

Seznam kurzu    HOTOVO
GET /kurzy?autoskola_id={id}
< 200
< Content-Type: application/json
{ "kurzy": [
    { "id": 1, "identifikacni-cislo": "A201301", "typ": "A", "stav": "otevreny", "datum-od": "2013-01-01", "datum-do": "2013-04-01",
      "hodiny-teorie": [
          {"datum": "2013-01-01", "zacatek": "13:00", "konec": "15:00", "vyucujici": "Novak", "typ-vyuky": "teorie"},
          {"datum": "2013-01-02", "zacatek": "14:00", "konec": "16:00", "vyucujici": "Novakova", "typ-vyuky": "zdravoveda"}
    ]},
    { "id": 2, "identifikacni-cislo": "B201302", "typ": "B", "stav": "otevreny", "datum-od": "2013-01-01", "datum-do": "2013-04-01",
      "hodiny-teorie": [
          {"datum": "2013-01-01", "zacatek": "13:00", "konec": "15:00", "vyucujici": "Novak", "typ-vyuky": "teorie"},
          {"datum": "2013-01-02", "zacatek": "14:00", "konec": "16:00", "vyucujici": "Novakova", "typ-vyuky": "zdravoveda"}
    ]},
    { "id": 3, "identifikacni-cislo": "T201305", "typ": "T", "stav": "otevreny", "datum-od": "2013-01-01", "datum-do": "2013-04-01",
      "hodiny-teorie": [
          {"datum": "2013-01-01", "zacatek": "13:00", "konec": "15:00", "vyucujici": "Novak", "typ-vyuky": "teorie"},
          {"datum": "2013-01-02", "zacatek": "14:00", "konec": "16:00", "vyucujici": "Novakova", "typ-vyuky": "zdravoveda"}
    ]}
] }

Detail kurzu    HOTOVO
GET /kurzy/{id}
< 200
< Content-Type: application/json
{ "id": 1, "identifikacni-cislo": "A201301", "typ": "A", "stav": "otevreny", "datum-od": "2013-01-01", "datum-do": "2013-04-01", "pocet-studentu": 15,
  "hodiny-teorie": [
        {"datum": "2013-01-01", "zacatek": "13:00", "konec": "15:00", "vyucujici": "Novak", "typ-vyuky": "teorie"},
        {"datum": "2013-01-02", "zacatek": "14:00", "konec": "16:00", "vyucujici": "Novakova", "typ-vyuky": "zdravoveda"}
  ], "studenti": [
        { "id": 1, "jmeno": "Martin", "prijmeni": "ZborilGaraz", "autoskola-id": 1, "matricni-cislo": 26549562 },
        { "id": 2, "jmeno": "Jacob", "prijmeni": "VjelDoPole", "autoskola-id": 1, "matricni-cislo": 26549562 },
        { "id": 3, "jmeno": "Lukas", "prijmeni": "SrazilChodce", "autoskola-id": 1, "matricni-cislo": 26549562 }
  ], "dokumenty" : [ { "id": 1, "nazev" : "Prihlaska PDF", "datum-vlozeni" : "2011-05-01" } ]
}

Vytvoreni kurzu
POST /kurzy
> Content-Type: application/json
{ "typ": "A", "stav": "otevreny", "datum-od": "2013-01-01", "datum-do": "2013-04-01", "pocet-studentu": 15 },
< 201
< Content-Type: application/json
{ "id": 1, "identifikacni-cislo": "A201301", "typ": "A", "stav": "otevreny", "datum-od": "2013-01-01", "datum-do": "2013-04-01", "pocet-studentu": 15 }

Odstraneni kurzu    HOTOVO
DELETE /kurzy/{id}
< 200


--
Vozidla Resources
The following is a section of resources related to Vozidla
--

Seznam vozidel
GET /vozidla
< 200
< Content-Type: application/json
{ "vozidla": [
    { "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1},
    { "id": 2, "znacka": "Skoda", "model": "Octavia", "vin": "LJP05GFD5541111", "autoskola-id": 2 }
] }


Detail vozidla  HOTOVO
GET /vozidla/{id}
< 200
< Content-Type: application/json
{ "id": 1, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1, "pocet-km" : 155555, "datum-stk": "2014-05-01", 
  "pocatecni-stav-km": 30000, "typ" : "osobní automobil", "rok-vyroby" : 2007, "spz" : "2E2 2222", "prumerna-spotreba" : 6.8,
  "jizdy" : [
    { "id": 1, "datum": "2013-01-01", "ucitel": 2, "vozidlo": 1, "zak": 1, "cas-od": "15:00", "cas-do": "17:00", "pocet-ujetych-km" : 15, "spotreba" : 6.7 },
    { "id": 2, "datum": "2013-01-01", "ucitel": 1, "vozidlo": 1, "zak": 5, "cas-od": "17:00", "cas-do": "18:50", "pocet-ujetych-km" : 16, "spotreba" : 7.1 }
  ], "dokumenty" : [
    { "id": 1, "nazev" : "STK a emise", "datum-vlozeni" : "2011-05-01" },
    { "id": 2, "nazev" : "STK a emise 2", "datum-vlozeni" : "2013-05-01" }
  ] }

Vytvoreni noveho vozidla    HOTOVO
POST /vozidla
> Content-Type: application/json
{ "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1, "datum-stk": "2014-05-01", 
  "pocatecni-stav-km": 30000, "typ" : "osobní automobil", "rok-vyroby" : 2007, "spz" : "2E2 2222" }
< 201
< Content-Type: application/json
{ "id": 3, "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1, "datum-stk": "2014-05-01", 
  "pocatecni-stav-km": 30000, "typ" : "osobní automobil", "rok-vyroby" : 2007, "spz" : "2E2 2222" }

Upraveni vozidla    HOTOVO
PUT /vozidla/{id}
> Content-Type: application/json
{ "znacka": "Ford", "model": "Focus", "vin": "LJP05GFD5548913", "autoskola-id": 1, "datum-stk": "2014-05-01", 
  "pocatecni-stav-km": 30000, "typ" : "osobní automobil", "rok-vyroby" : 2007, "spz" : "2E2 2222" }
< 200
< Content-Type: application/json
{ "znacka": "Ford", "model": "Focus", "vin": "vracene vin", "autoskola-id": 1, "datum-stk": "2014-05-01", 
  "pocatecni-stav-km": 30000, "typ" : "osobní automobil", "rok-vyroby" : 2007, "spz" : "2E2 2222" }

Odstraneni vozidla    HOTOVO
DELETE /vozidla/{id}
< 200


Odstraneni dokumentu    HOTOVO
DELETE /dokumenty/{id}
< 200


--
Vozidla Resources
The following is a section of resources related to Vozidla
--

Kniha jizdy
GET /jizdy
< 200
< Content-Type: application/json
{ "jizdy": [
    { "id": 1, "datum": "2013-01-01", "ucitel": 2, "vozidlo": 1, "zak": 1, "cas-od": "15:00", "cas-do": "17:00", "pocet-ujetych-km" : 15, "spotreba" : 6.7 },
    { "id": 2, "datum": "2013-01-01", "ucitel": 1, "vozidlo": 1, "zak": 5, "cas-od": "15:00", "cas-do": "17:00", "pocet-ujetych-km" : 16, "spotreba" : 7.1 }
] }

Vytvoreni nove jizdy    HOTOVO
POST /jizdy
> Content-Type: application/json
{ "datum": "2013-01-01", "ucitel": 2, "vozidlo": 1, "zak": 1, "cas-od": "15:00", "cas-do": "17:00", "pocet-ujetych-km" : 15, "spotreba" : 6.7 },
< 201
< Content-Type: application/json
{ "id": 3, "datum": "2013-01-01", "ucitel": 2, "vozidlo": 1, "zak": 1, "cas-od": "15:00", "cas-do": "17:00", "pocet-ujetych-km" : 15, "spotreba" : 6.7 }

Odstraneni jizdy    HOTOVO
DELETE /jizdy/{id}
< 200